[package]
name = "rust_lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = "0.26.1"
ironfish = { path = "../ironfish/ironfish-rust" }

[lib]
crate-type = ["staticlib", "cdylib"]