[package]
name = "rust_lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
const-hex = "1.12.0"
ironfish = { version = "0.3.0", features = ["download-params"] }
num = "0.4.1"
num-derive = "0.4.2"
num-traits = "0.2.18"
tokio = { version = "1.38.1", features = ["full"] }
tokio-rayon = "2.1.0"
thiserror = "1.0"
uniffi = { version = "0.28.0", features = ["tokio"] }
zune-inflate = "0.2.54"

[lib]
crate-type = ["staticlib", "cdylib"]
