[package]
name = "rust_lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ironfish = { path = "../ironfish/ironfish-rust" }
num = "0.4.1"
num-derive = "0.4.2"
num-traits = "0.2.18"
thiserror = "1.0"
uniffi = "0.26.1"

[lib]
crate-type = ["staticlib", "cdylib"]
