name: Build
on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build_template.yaml
        with:
          os: macos-latest